image: alpine:3.15.1

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
    - build

build_image:
  stage: build
  tags:
    - window
    - arm
    - shell
  before_script:
    - cd src/main #changing directory into the folder where the application file
  script:
    - .\gradlew build ##building the artifact
